server:
  servlet:
    context-path: /reversi_online
  port: your_server_port_here

spring:
  data:
    redis:
      host: localhost
      port: your_redis_port_here
      password: your_password_here
      database: database_number
